version: 2

sources:
  - name: axis_core
    tables:
      - name: walletdetails
      - name: transactiondetails
      - name: walletprofiles
      

  - name: dbt-dimensions
    tables:
      - name: inc_transactions_dimension
      - name: inc_stg_wallets
      - name: inc_stg_wallets_2
      - name: inc_wallets_dimension
