version: 2

sources:
  - name: axis_core
    tables:
      - name: _airbyte_raw_walletdetails
      - name: _airbyte_raw_transactiondetails
      - name: _airbyte_raw_walletprofiles
      

  - name: dbt-dimensions
    tables:
      - name: transactions_dimension
      - name: stg_wallets
      - name: stg_wallets_2
      - name: wallets_dimension
