version: 2

sources:
  - name: axis_core
    tables:
      - name: walletdetails
      - name: transactiondetails
      - name: walletprofiles
      

  - name: dbt-dimensions
    tables:
      - name: inc_transactions_dimension
      - name: inc_transactions_stg
      - name: inc_transactions_stg_new
      - name: inc_transactions_stg_update

      - name: inc_wallets_dimension
      - name: inc_wallets_stg
      - name: inc_wallets_stg_new
      - name: inc_wallets_stg_update
      - name: inc_wallets_stg_exp
      - name: inc_wallets_stg_no_change

